#!/usr/bin/env python3
"""
PM Agent 规则检查 + 自约束脚本
每次 spawn subagent / 编辑代码文件前自动运行，确保规则被遵守。

Usage:
  python3 scripts/check_rules.py spawn <AGENT> <MESSAGE>
  python3 scripts/check_rules.py verify
  python3 scripts/check_rules.py check-action <ROLE> <ACTION> [--file PATH]
  python3 scripts/check_rules.py audit-git [--since DAYS]
"""

import sys
import json
import os
import re
from pathlib import Path
from datetime import datetime, timezone, timedelta

WORKSPACE = Path("/workspace/projects/workspace")
MESSAGE_FILE = WORKSPACE / "agents/project-admin/logs/agent-messages.json"
LAST_MSG_FILE = WORKSPACE / "agents/project-admin/logs/last_spawn_check.json"

# === CODE FILE PATTERNS - PM MUST NOT TOUCH ===
CODE_EXTENSIONS = {
    '.ts', '.tsx', '.js', '.jsx', '.mjs', '.cjs',
    '.py', '.java', '.go', '.rb', '.php',
    '.css', '.scss', '.less', '.html',
    '.sql', '.prisma',
    '.json', '.yaml', '.yml',
    '.dockerfile', '.Dockerfile',
}

# Directories where PM is allowed to edit files
PM_ALLOWED_DIRS = {
    'docs/', '.github/', 'scripts/',
    'agents/', 'memory/', 'HEARTBEAT.md', 'MEMORY.md',
    'AGENTS.md', 'SOUL.md', 'CRITICAL_RULES.md', 'TOOLS.md',
    'PROJECT-WIKI.md', 'student-management-spec/',
}

# Files that are auto-generated by dashboard updates - excluded from audit
AUTO_GENERATED_FILES = {
    'multi-agent-dashboard.html',
    'version.json',
    'agent-status.json',
    'agent-messages.json',
}

def get_agent_role() -> str:
    """Detect current agent role. Default to 'pm' if running from main session."""
    # Check if we can detect from environment
    agent_id = os.environ.get('OPENCLAW_AGENT_ID', '').lower()
    if 'dev' in agent_id:
        return 'dev'
    if 'qa' in agent_id:
        return 'qa'
    if 'ops' in agent_id or 'devops' in agent_id:
        return 'ops'
    # Default: PM (main session)
    return 'pm'

def is_code_file(filepath: str) -> bool:
    """Check if a file is a code file that PM should not edit directly."""
    ext = Path(filepath).suffix
    return ext in CODE_EXTENSIONS

def is_pm_allowed_file(filepath: str) -> bool:
    """Check if this file is in the whitelist for PM edits."""
    rel = Path(filepath).as_posix()
    for allowed in PM_ALLOWED_DIRS:
        if rel.startswith(allowed) or rel == allowed:
            return True
    return False

def check_last_message():
    """检查最近一次 spawn 是否已记录"""
    if not MESSAGE_FILE.exists():
        return False, "agent-messages.json 不存在"

    messages = json.loads(MESSAGE_FILE.read_text())
    if not messages:
        return False, "没有消息记录"

    last_msg = messages[-1]
    last_time = last_msg.get("timestamp", "")
    last_type = last_msg.get("type", "")

    return True, f"最后消息: {last_type} at {last_time}"

def log_spawn(agent: str, message: str):
    """记录一次 spawn 操作"""
    if not MESSAGE_FILE.exists():
        MESSAGE_FILE.parent.mkdir(parents=True, exist_ok=True)
        MESSAGE_FILE.write_text("[]")

    messages = json.loads(MESSAGE_FILE.read_text())

    new_msg = {
        "timestamp": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "from": "PM",
        "to": agent,
        "message": message[:100],
        "type": "spawn_check",
        "agent_status": {
            "agent": "PM",
            "status": "running",
            "task": message[:50]
        }
    }

    messages.append(new_msg)
    messages = messages[-200:]

    MESSAGE_FILE.write_text(json.dumps(messages, ensure_ascii=False, indent=2))
    return new_msg

def update_dashboard():
    """Trigger dashboard update."""
    try:
        import subprocess
        result = subprocess.run(
            ["python3", str(WORKSPACE / "skills/multi-agent-dashboard/scripts/update_dashboard.py")],
            capture_output=True, text=True, timeout=120,
            cwd=str(WORKSPACE)
        )
        if result.returncode == 0:
            return True, "Dashboard 已更新"
        else:
            return False, f"Dashboard 更新失败: {result.stderr[:100]}"
    except Exception as e:
        return False, f"Dashboard 更新失败: {str(e)[:100]}"

def check_action(role: str, action: str, filepath: str = None):
    """
    ENFORCEMENT: Check if this action is allowed for the given role.

    Returns (allowed: bool, reason: str)
    If role=PM and action=edit/write/patch on a code file → BLOCKED
    """
    role = role.lower()

    # PM allowed actions without restriction
    pm_safe_actions = {
        'read', 'search', 'list', 'inspect', 'describe',
        'spawn', 'assign', 'log', 'notify', 'report',
    }

    if action in pm_safe_actions:
        return True, f"✅ {role.upper()}: {action} 安全操作，允许"

    # PM trying to modify code → BLOCKED
    if role in ('pm', 'main') and action in ('edit', 'write', 'patch', 'apply_patch', 'commit_code', 'modify'):
        if filepath:
            if is_pm_allowed_file(filepath):
                return True, f"✅ PM: 允许编辑文件 {filepath} (配置/文档白名单)"

            if is_code_file(filepath):
                return False, (
                    f"\n{'='*60}"
                    f"\n🚫 BLOCKED: PM 不允许直接编辑代码文件!"
                    f"\n{'='*60}"
                    f"\n  文件: {filepath}"
                    f"\n  原因: SOUL.md §2.2 规定 PM 不直接执行其他 Agent 工作"
                    f"\n"
                    f"\n  正确流程:"
                    f"\n  1. write_message.py --from PM --to DEV --type assign"
                    f"\n  2. sessions_spawn(DEV) 让 DEV 修改代码"
                    f"\n"
                    f"\n  如果这是紧急修复 (P0 系统不可用):"
                    f"\n   手动忽略此检查，但24小时内必须补 DEV 审查 + 文档"
                    f"\n{'='*60}"
                )

        # No file specified, but action is 'edit' or 'write' → likely code
        return False, (
            f"\n{'='*60}"
            f"\n🚫 BLOCKED: PM 不允许直接编辑代码!"
            f"\n{'='*60}"
            f"\n  你正在尝试以 PM 身份修改代码，这违反了 SOUL.md 规则。"
            f"\n"
            f"\n  正确做法："
            f"\n  1. write_message --from PM --to DEV --type assign"
            f"\n  2. sessions_spawn(DEV)"
            f"\n{'='*60}"
        )

    # DEV/QA/OPS → allowed
    return True, f"✅ {role.upper()}: {action} 操作允许"

def audit_git(since_days: int = 7):
    """
    Audit git log for PM violations: commits by PM that modify code files.

    Returns list of violations.
    """
    violations = []
    try:
        repo_path = WORKSPACE / ".." / "school-admin-system"
        if not repo_path.exists():
            repo_path = WORKSPACE
        import subprocess
        since_date = (datetime.now() - timedelta(days=since_days)).strftime("%Y-%m-%d")

        result = subprocess.run(
            ["git", "log", f"--since={since_date}", "--format=%H|%an|%s", "--name-only"],
            capture_output=True, text=True, timeout=30,
            cwd=str(repo_path)
        )

        if result.returncode != 0:
            return [], [f"git log failed: {result.stderr[:100]}"]

        current_commit = None
        current_author = None
        current_msg = None
        current_files = []

        for line in result.stdout.split('\n'):
            if '|' in line and line.count('|') >= 2:
                # New commit
                if current_commit and current_author and current_files:
                    author_lower = current_author.lower()
                    # Check if author is specifically PM Agent (not openclaw-memory-sync)
                    is_pm_commit = (
                        'pm agent' in author_lower or
                        author_lower.startswith('pm')
                    )
                    # Filter: only catch real code file changes (exclude auto-generated files)
                    code_files = [
                        f for f in current_files
                        if is_code_file(f)
                        and not is_pm_allowed_file(f)
                        and Path(f).name not in AUTO_GENERATED_FILES
                    ]
                    if is_pm_commit and code_files:
                        violations.append({
                            'commit': current_commit[:8],
                            'author': current_author,
                            'message': current_msg[:80],
                            'code_files': code_files,
                        })
                parts = line.split('|', 2)
                current_commit = parts[0]
                current_author = parts[1]
                current_msg = parts[2]
                current_files = []
            elif line.strip() and current_commit:
                current_files.append(line.strip())

        # Last commit
        if current_commit and current_author and current_files:
            author_lower = current_author.lower()
            is_pm_commit = (
                'pm agent' in author_lower or
                author_lower.startswith('pm')
            )
            code_files = [
                f for f in current_files
                if is_code_file(f)
                and not is_pm_allowed_file(f)
                and Path(f).name not in AUTO_GENERATED_FILES
            ]
            if is_pm_commit and code_files:
                violations.append({
                    'commit': current_commit[:8],
                    'author': current_author,
                    'message': current_msg[:80],
                    'code_files': code_files,
                })

    except Exception as e:
        return [], [str(e)[:200]]

    return violations, []

def main():
    if len(sys.argv) < 2:
        print(__doc__)
        sys.exit(1)

    command = sys.argv[1]

    if command == "spawn":
        if len(sys.argv) < 4:
            print("用法: check_rules.py spawn <AGENT> <MESSAGE>")
            sys.exit(1)

        agent = sys.argv[2]
        message = sys.argv[3]

        msg = log_spawn(agent, message)
        print(f"✅ Spawn 已记录: PM → {agent}")
        print(f"   消息: {message[:60]}...")
        print(f"   时间: {msg['timestamp']}")

        ok, info = update_dashboard()
        print(f"{'✅' if ok else '⚠️'} {info}")

    elif command == "verify":
        ok, info = check_last_message()
        print(f"{'✅' if ok else '⚠️'} {info}")

    elif command == "check-action":
        if len(sys.argv) < 4:
            print("用法: check_rules.py check-action <ROLE> <ACTION> [--file PATH]")
            sys.exit(1)

        role = sys.argv[2]
        action = sys.argv[3]

        filepath = None
        if '--file' in sys.argv:
            idx = sys.argv.index('--file')
            if idx + 1 < len(sys.argv):
                filepath = sys.argv[idx + 1]

        allowed, reason = check_action(role, action, filepath)
        print(reason)
        sys.exit(0 if allowed else 1)

    elif command == "audit-git":
        since = 7
        if '--since' in sys.argv:
            idx = sys.argv.index('--since')
            if idx + 1 < len(sys.argv):
                try:
                    since = int(sys.argv[idx + 1])
                except ValueError:
                    pass

        violations, errors = audit_git(since)

        if errors:
            print("⚠️  审计错误:")
            for e in errors:
                print(f"  - {e}")

        if violations:
            print(f"\n🚨 发现 {len(violations)} 条 PM 违规修改代码记录 (过去 {since} 天):")
            print(f"{'='*60}")
            for v in violations:
                print(f"  commit: {v['commit']}")
                print(f"  author: {v['author']}")
                print(f"  msg:    {v['message']}")
                print(f"  违规文件:")
                for f in v['code_files'][:5]:
                    print(f"    - {f}")
                if len(v['code_files']) > 5:
                    print(f"    ... 还有 {len(v['code_files']) - 5} 个")
                print()
            sys.exit(2)
        else:
            print(f"✅ 审计通过: 过去 {since} 天没有发现 PM 违规修改代码记录")
            sys.exit(0)

    else:
        print(f"未知命令: {command}")
        print(__doc__)
        sys.exit(1)


if __name__ == "__main__":
    main()
